# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

command: 
  install-shellcheck:
    steps:
      - run: sudo apt install shellcheck -y


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  docker-executor: 
    docker:
      - image: cimg/base:2022.04
jobs:
  shell-check:
    executor: docker-executor
    steps:
      - checkout
      - install-shellcheck

workflows:
  shell-check:
    jobs: 
      - shell-check
      