# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1.2

parameters:
  image-tag:
    type: string
    default: "current"
  bashdir:
    type: string
    default: "./support/bash"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  docker-executor: 
    docker:
      - image: cimg/base:2022.04
jobs:
  shellcheck:
    docker-executor: docker
    docker:
      - image: cimg/base:2022.04
    steps:
      - shellcheck/check:
            dir: << pipeline.parameters.bashdir >>
      
workflows:
  shell-check:
    jobs: 
      - shellcheck:
          dir: ./support/bash
