version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1.2

executors:
  docker-executor: 
    docker:
      - image: cimg/base:2022.04
    resource_class: small
workflows:
  shell-check:
    jobs: 
      - shellcheck/check:
          dir: ./support/bash
