# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  docker-executor:
    docker:
      - image: cimg/base:2022.04
jobs:
  shellcheck:
    parameters:
      bashdir:
        type: string
        default: support/bash
    executor: docker-executor
    resource_class: small
    steps:
      - shellcheck/check:
          dir: << parameters.bashdir >>

workflows:
  shell-check:
    jobs:
      - shellcheck
