# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  docker-executor: 
    docker:
      - image: cimg/base:latest
jobs:
  shell-check:
    executor: docker-executor
    steps:
      - checkout
      - command: sudo apt install shellcheck
workflows:
  shell-check:
    jobs: 
      - shell-check