# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands: 
  install-shellcheck:
    steps:
      - run: sudo apt install shellcheck -y
  shell-check:
    steps:
      - run: bash support/bash/bash-shellcheck.sh 
      - run: echo $CIRCLE_SHA1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  docker-executor: 
    docker:
      - image: cimg/base:2022.04
      
jobs:
  shell-check:
    executor: docker-executor
    resource_class: small
    steps:
      - checkout
      - install-shellcheck
      - shell-check 
    
workflows:
  shell-check:
    jobs: 
      - shell-check
      